# Logitech G29 constants.
# Raw packet values are kept as ints for easier reading.

# DEVICE
VENDOR_ID = 1133
PRODUCT_ID = 49743

# EFFECT SLOT
SLOT_RANGE = [0x1, 0xF]

# AXIS
GAME_PAD = 0
BUTTON_MISC = 1
BUTTON_PLUS = 2
BUTTON_MISC2 = 3
STEERING_COARSE = 4
STEERING_FINE = 5
PEDAL_ACCELERATOR = 6
PEDAL_BRAKE = 7
PEDAL_CLUTCH = 8

# GAME PAD (axis 0)
GAME_PAD_NIL = 8

GAME_PAD_UP = 0
GAME_PAD_DOWN = 4
GAME_PAD_RIGHT = 2
GAME_PAD_LEFT = 6

GAME_PAD_X = 24
GAME_PAD_SQUARE = 40
GAME_PAD_CIRCLE = 72
GAME_PAD_TRIANGLE = 136

# MISC (axis 1)
MISC_NIL = 0
MISC_R2 = 4
MISC_R3 = 64
MISC_L2 = 8
MISC_L3 = 128
MISC_SHARE = 16
MISC_OPTIONS = 32

# PLUS (axis 2)
BUTTON_PLUS_NIL = 0
BUTTON_PLUS_ON = 128

# MISC2 (axis 3)
MISC2_NIL = 0
MISC2_MINUS = 1
MISC2_TRACK_RIGHT = 2
MISC2_TRACK_LEFT = 4
MISC2_BACK = 8
MISC2_PS = 16
